### ISSUE TITLE
elite frontier crashes

### ISSUE THREAD

**Issue by stsp** [stsp/fdpp#105]
... at start.

**Comment by stsp** [comment]
Horrible freedos bugs that managed to
not manifest themselves in freedos...

**Comment by jschwartzenberg** [comment]
Are you upstreaming your fixes to freedos? Maybe it would improve compatibility overall?

**Comment by stsp** [comment]
We are upstream.
They proved the inability of being
an upstream many many times.
Example:
https://sourceforge.net/p/freedos/mailman/message/36613159/
(one of many).
Besides, fdpp is an open-source project.
Any upstream that cares (not the one that
don't) can get any fixes for free.

**Comment by stsp** [comment]
Sooner or later we will also provide the
qemu-ready images. After that, I would be
very surprised to find any reason to prefer
freedos over fdpp.

**Comment by jschwartzenberg** [comment]
Yes, that makes sense. The only usage I can think of is pre-386 systems.

**Comment by stsp** [comment]
In principle I can resurrect the real-mode
build to fill even that gap, but I am afraid
this contradicts the fdpp goals of using only
the modern technologies.
So if there is a pre-386 "market", I'll leave
it to freedos. :)
Besides, it is technically impossible for them
to be our upstream. We use the most modern
tools like gdb, sanitizers, latest C++ features
and all that. And how do they debug a simplest
bug, with an asm-level real-mode debugger?
So it is absolutely unbelievable for them to offer
anything useful to us. Given that they also
reject to get anything useful _from_ us, I see
no reason in such upstream/downstream relations
that you assumed. It simply doen't work that way.

**Comment by stsp** [comment]
Please check the bug #106.
