### ISSUE TITLE
elite1 hangs

### ISSUE THREAD

**Issue by stsp** [stsp/fdpp#106]
... at startup, after selecting sound card.
Well, most of games do not work, fdpp sucks.

**Comment by stsp** [comment]
This works for me now.
@jschwartzenberg could you please test
if it was related to that "bad kvm" thing?

**Comment by jschwartzenberg** [comment]
Is that this game? https://www.myabandonware.com/game/elite-ao

**Comment by stsp** [comment]
Ah, sorry, should be this one:
https://www.myabandonware.com/game/elite-plus-155

**Comment by jschwartzenberg** [comment]
It gives me `Packed file is corrupt` in FreeDOS.

**Comment by stsp** [comment]
Try `loadfix`

**Comment by jschwartzenberg** [comment]
Whoops I was actually using FDPP. Does it have a loadfix?

**Comment by stsp** [comment]
It does.

**Comment by jschwartzenberg** [comment]
It runs here.

**Comment by stsp** [comment]
Yes but does it run on the "broken kvm" PC?

**Comment by jschwartzenberg** [comment]
Yeah runs fine. It doesn't seem to be related to that.

**Comment by stsp** [comment]
OK, then lets close that.
