### ISSUE TITLE
unlink UMB chain on exec

### ISSUE THREAD

**Issue by stsp** [stsp/fdpp#108]
Currently `lh` of comcom32 has a big problem:
if command.com is loaded with it, the UMB chain
is not unlinked.
This was worked-around here:
https://github.com/stsp/comcom32/commit/629fdd3ec444c5714a7e2c9e0e88a618c0e55e51
but freecom doesn't have a similar work-around.
So I am going to forcibly unlink UMB on exec.
@ecm-pushbx what do you think?

**Comment by ecm-pushbx** [comment]
I don't think you should unconditionally unlink UMBs. Although it is an unusual situation to keep it, the linking of UMBs should be preserved by the kernel. If you want to do SHELLHIGH without leaving UMBs linked during the process's running, you should use FreeDOS's mode 80h. Or use 01h (load but do not execute) then unlink UMBs then start to execute the shell. (That has to be done in the CONFIG.SYS processing / initialisation done by the kernel, so DJGPP lacking support for either mode is not relevant.)

**Comment by stsp** [comment]
> you should use FreeDOS's mode 80h.

Its quite undocumented.
Is it implemented elsewhere?

> That has to be done in the CONFIG.SYS processing /
> initialisation done by the kernel, so DJGPP lacking support for either mode is not relevant.

The problem is not only SHELLHIGH (in fact I am
not even sure SHELLHIGH is a problem at all).
The problem is `lh` that you implemented in comcom32.
