### ISSUE TITLE
Tetris Classic crashes fdpp

### ISSUE THREAD

**Issue by jschwartzenberg** [stsp/fdpp#109]
Same game as:
https://github.com/stsp/dosemu2/issues/99
https://github.com/stsp/dosemu2/issues/492

Starting it allows selecting a video mode in the menu, but then fdpp crashes:
```
ERROR: fdpp: abort at ./farptr.hpp:542
```

More info about the game:
http://www.abandonia.com/en/games/914/Tetris+Classic.html

**Comment by stsp** [comment]
Works on freedos?

**Comment by stsp** [comment]
Should now work.
Strictly speaking this is a freedos  bug.
But the one that won't trigger in freedos.
fdpp adds a lot of instrumentation, and
in this case the array bound checking
instrumentation found the UB code
(that would otherwise work properly in
practice).
