### ISSUE TITLE
fdpp (+dosemu) crashes; MCB corruption when DEBUG.COM tries to load a .COM file

### ISSUE THREAD

**Issue by Baron-von-Riedesel** [stsp/fdpp#123]
**Describe the bug**
FDPP crashes, apparently because of an corrupted MCB chain.

**To Reproduce**
I start FD debug.com without a parameter:
C:\>debug

Inside debug, i use the N command to set the name of an executable to load:
-N simple.com

Then I tell debug to load that program:
-L

After that, I get an I/O error reported from DOS. When I choose C/ancel, FDPP crashes.

When I deactivate FDPP (by renaming C:\\\_KERNEL.SY\_ to C:\\KERNEL.SYS), the error does NOT appear and everything works as it should.

**Attach the binaries or provide an URL**
[fdpp_crash.zip](https://github.com/stsp/dosemu2/files/4117853/fdpp_crash.zip)

**Attach the log**
[boot.log.1.zip](https://github.com/stsp/dosemu2/files/4117858/boot.log.1.zip)

**Comment by stsp** [comment]
But #97 will break with that patch.
Any idea how to keep working both...

**Comment by Baron-von-Riedesel** [comment]
Applied the patch and it works! :)

> Any idea how to keep working both...
Hopefully you don't ask me...

**Comment by stsp** [comment]
> Hopefully you didn't ask me...

Why not?
Its an interesting question.
If you change PSP parent to itself
(self-parented PSP) and try to terminate
it, freedos crashes, as it stores the pointer
to registers (psp->ps_stack) in the parent
PSP, which is then inaccessible. But MS
and PC-DOS do not crash, even though
it may be wrong to terminate the self-parented
PSP. I thought it might be a good idea
to store the pointer to registers image
in current PSP:2e - then it became possible
to call 4c even on self-parented PSP.
But in this particular case something
goes wrong. Maybe debug changes PSP:2e
by hands?
I think someone needs to investigate how
exactly MS-DOS uses PSP:2e on 4c.

**Comment by stsp** [comment]
Should now be fixed, but I am still not
sure if this is what MS-DOS does or not.

**Comment by Baron-von-Riedesel** [comment]
> Maybe debug changes PSP:2e by hands?

Yes, it does. See SPSAV in debug.asm. it's used 2 times.

**Comment by stsp** [comment]
Whatever it writes to 2e, will be used
on 0x4c by fdpp, ignored by freedos,
??? by ms-dos. What is the expected
behaviour?

**Comment by stsp** [comment]
Nope, doesn't work properly.

**Comment by stsp** [comment]
Yes, indeed SPSAV is a problem.
It seems to be adjusting SPSAV not
in the last psp in a chain, but in the
parent of the last psp.
Could you please explain the logic?
How does it get the psp for adjusting SPSAV?

**Comment by Baron-von-Riedesel** [comment]
> How does it get the psp for adjusting SPSAV?
It's always the debugger's PSP:2E location that is read or written. Since it is a .COM file, DS points to the PSP.

> Could you please explain the logic?

AFAIU there are 2 locations:
1. when loading a debuggee with int 21h, ax=4B01h, DEBUG reads immediately after that call the value at PSP:2Eh, and subtracts it from the current value of register SP. The result is stored in spadjust.

2. Whenever running/tracing the debuggee, DEBUG uses the current SP (of DEBUG), subtracts the value in spadjust from it and stores the result in the debugger's PSP:2Eh.

**Comment by Baron-von-Riedesel** [comment]
I guess it's to ensure that DOS, when the debuggee terminates, does not overwrite (parts of) the debugger's stack.

**Comment by stsp** [comment]
But if you 'l' the debugee and then 'q',
then it seems the current PSP that is
being 4c'ed, is not the original PSP of
the debugger. Otherwise that would
work fine.

**Comment by stsp** [comment]
I.e. it seems another PSP is created for
the debugee by copying the PSP of the
debugger. Then the debugee's PSP gets
4c'ed. Is this correct?

**Comment by Baron-von-Riedesel** [comment]
> But if you 'l' the debugee and then 'q',

In this case, DEBUG first terminates the debuggee (with int 21h, ah=4Ch), and then terminates itself with Int 20h.

> I.e. it seems another PSP is created for the debugee by copying the PSP of the debugger. 

The debuggee's PSP is created by either an Int 21h, ax=4B01h ( the 'l' command ) or an int 21h, ah=55h ( the "dummy" debuggee, which is created when no "real" debuggee exists ).

**Comment by stsp** [comment]
But when it terminates the debugee
with 4c, it seems to expect the spsav
is being used to restore stack. And
spsav is in the parent psp of debugee.
So it seems to insist on the logic where
parent's 2e is used by 4c. Is this correct?

**Comment by stsp** [comment]
How difficult would it be to make an
experiment to use SPSAV of current
PSP rather than always debugger PSP?
I just want to make sure that altering
parent's spsav is the only expected
way to affect 4c.

**Comment by Baron-von-Riedesel** [comment]
> How difficult would it be to make an...

Its easy to modify, but IMO can't work, because the field PSP:[002Eh] of the debuggee is modified by DOS in virtually each DOS call that the debuggee is making.

**Comment by stsp** [comment]
Not under fdpp.
That's the main difference.
But I suppose its a wrong difference...

**Comment by Baron-von-Riedesel** [comment]
> So it seems to insist on the logic where
> parent's 2e is used by 4c. Is this correct?

IMO Yes. "Normally", when one program calls another, it does this by using int 21h, ax=4B00h. The stack pointer of the caller is saved in its PSP:002Eh field, along with the current register values of the caller. When the called program terminates with ax=4C00h, the register values of the caller can ONLY be restored by using PSP:002Eh of the caller.

**Comment by stsp** [comment]
OK, thanks for confirming the previous
freedos logic. So I need to revert my changes.
But the question is then how does MS_DOS
correctly handle the termination of self-parented
PSP? It somehow gets the right registers and
avoids the crash, whereas freedos crashes.
Maybe it uses SDA to get caller regs?

**Comment by Baron-von-Riedesel** [comment]
> whereas freedos crashes.

Does FreeDos really crash? If I make debug do a far jump using the dword stored at PSP:000Ah of the FreeCOM instance it displays:

Cannot terminate permanent FreeCOM instance
System halted ... reboot or power off now

I admit it's not far better than a crash, but at least it's a controlled halt :))

**Comment by stsp** [comment]
It would really crash, but freecom installs
the termination handler to restore parent
psp. Any simple test that doesnt restore
parent, would crash.

**Comment by stsp** [comment]
Please see #97 for more info.
I didn't want to do that patch. :)
But there is something still unknown
happens.

**Comment by stsp** [comment]
OT: have you noticed that NDN-64 uses
the 64bit DPMI? I wonder what is that all about.

**Comment by Baron-von-Riedesel** [comment]
> OT: have you noticed that NDN-64 uses the 64bit DPMI? 

Yes. "Candyman" anounced it in the bttr-forum [http://www.bttr-software.de/forum/forum_entry.php?id=15537](url)

There are probably more samples on his/her Google drive. The extender is called DX64, also anounced in the bttr-forum [(](http://www.bttr-software.de/forum/forum_entry.php?id=15853)

Haven't read any docs about it. Most likely it doesn't exist (yet).

**Comment by stsp** [comment]
Since this bug is real, I just reverted to
the old logic. How to make that the MS-DOS
way, is still unclear.
