### ISSUE TITLE
dosemu + fdpp: ms-dos command.com does not "find" fdppauto.bat

### ISSUE THREAD

**Issue by Baron-von-Riedesel** [stsp/fdpp#127]
**Describe the bug**
command.com from MS-DOS 7.1 (Win98 SE) claims that it cannot find fdppauto.bat

**To Reproduce**
just start dosemu with command.com of MS-DOS 7.1

The problem is most likely due to the standard FDPPAUTO.BAT using LFs instead of the CR/LF combination as EOL markers. If I rewrite the file with a DOS editor, the LFs will be substituted by CR/LF and command.com has no problems running fdppauto.bat anymore.

**Comment by stsp** [comment]
Should now be fixed, now command.com
from DOS-7.1 writes Incorrect dos version.
