### ISSUE TITLE
Volkov Commander hangs on start

### ISSUE THREAD

**Issue by j2969719** [stsp/fdpp#128]
**Describe the bug**
Volkov Commander(4.05) hangs on start. v4.99 seems work fine. Also Dosemu closes(boot.log attached) when I try to change the settings via vcsetup

**To Reproduce**
install and lauch vc or vcsetup

**Attach the binaries or provide an URL**
https://vc.kiev.ua/download/

**Attach the log**
https://pastebin.com/0yWit5Uy

**Comment by stsp** [comment]
fdpp-specific (no crash on freedos).

**Comment by stsp** [comment]
Should now be fixed, thanks!
These are the remaining "presents" from
freedos code. In that case they decided
to save a few push/pops, making an assumptions
about the compiler they use, but that breaks
on the compiler we use.

**Comment by j2969719** [comment]
work like a charm, thanks!
