### ISSUE TITLE
ERROR: redundant conversion for 0x7f69e0d8715e

### ISSUE THREAD

**Issue by andrewbird** [stsp/fdpp#133]
I'm thinking about adding some locking tests on dosemu2 for MFS and I need to compare the results against the same tests run on FAT image. If I understand correctly I need to load `share.exe` before locking functions are usable on any DOS, so what's the correct vendor and version of share to be used with FDPP?

**Comment by stsp** [comment]
I am not on the subject really, but I
thought with mfs we don't need share.exe.
IIRC share also was not needed to run
the locking tests on local fatfs.
Looking into RBIL, it seems share mostly
expand fcb structures to maintain the locking
info. So probably if you use fcb functions
and the local fs and some multitasker, then
you need share.exe. But this can be completely
wrong. :)

**Comment by andrewbird** [comment]
Thanks. I'll look into getting the tests working on FAT without share first. In the meantime I found this 
https://github.com/FDOS/share

**Comment by stsp** [comment]
From that file it seems it hooks int2f/ah=10h
and provides functions al=0xa0...0xa4.
But I can't find them in rbil. :(
So I still think its not needed.

**Comment by andrewbird** [comment]
Looks like FDPP/FreeDOS calls int2f/10a4 (lock_unlock), but only on local file systems. See SHARE_LOCK_UNLOCK in kernel/int2f.asm and DosLockUnlock() in kernel/dosfns.c.

**Comment by stsp** [comment]
As I said, not used for mfs.

**Comment by andrewbird** [comment]
Of course you are right about MFS, but I was asking what vendor/version of share I needed to run the test on FAT first. Anyway just so we know for later it seems that FreeDOS 1.20 share.com seems to work mostly fine on FDPP, and is necessary for my test using a FAT image. There is one strange thing though, after loading it I see some messages in the launching terminal
~~~
ERROR: redundant conversion for 0x7f69e0d8715e

ERROR: redundant conversion for 0x7f69e0d8715e
~~~
They occur even without running my test, but on simple operations like deleting a file. I could find that string in fdpp git, but not dosemu2.git. Is this even an FDPP bug as I'm loading a FreeDOS extension?

**Comment by stsp** [comment]
This is the sanity check that means that
fdpp found some inefficiency in the data
flow. Please attach the log.

**Comment by andrewbird** [comment]
I presume dosemu log, but with which debug options?

**Comment by andrewbird** [comment]
Oh the test is in my branch `travis-ci-15`, and can be run as 
`python3 test/test_dos.py PPDOSGITTestCase.test_fat_ds3_lock_twice` you'll need to grab a new binary file that has `share.com` inside from here:
http://www.spheresystems.co.uk/test-binaries/FR-DOS-1.20.tar

**Comment by andrewbird** [comment]
Or, thinking about it, you don't even need to run the test you only need to load share.com from the tarfile I linked to above.

**Comment by stsp** [comment]
```
C:\>share.com
SHARE installed.
 
C:\>ver /r
comcom32 v0.1
 Source Control Revision ID: git badd39dc5e73
 
Reported DOS version (Int21.3000): 5.00 OEM: FDh
Reported true DOS version (Int21.3306): 7.10
Version string (Int21.33FF): FDPP kernel 1.0rc1 [GIT: rc-1-2-g37e3547] (compiled
 Mar 20 2020)
C:\>
```

Log with any options should contain the stack trace.

**Comment by andrewbird** [comment]
Here you go, in this case it was triggered by `del d:\testit.bat`

[test.log](https://github.com/stsp/fdpp/files/4362987/test.log)

**Comment by stsp** [comment]
Could you please check now?

**Comment by andrewbird** [comment]
Yep that seems fine now, thanks!
