### ISSUE TITLE
Trying to understand the fdppkrnl.map

### ISSUE THREAD

**Issue by andrewbird** [stsp/fdpp#14]
I see there's a kernel map file, are the addresses contained within absolute DOS addresses or do they need to be offset by some value? I want to find the CDS so before I start chasing for it, I thought I'd look for something simple and obvious like the OS version. The MAP file has this
~~~
0079:0090      _os_setver_minor                                                 
0079:0091      _os_setver_major                                                 
0079:0092      _os_minor                                                        
0079:0093      _os_major                                                        
0079:0095      _version_flags                                                   
0079:0096*     os_release                                                       
~~~

But if I `d` that in dosdebug I don't see any recognisable values
~~~
0079:0090 6C F6 0F 08 FF FF 00 D9 00 00 10 31 C0 8E D8 A0  lv...Y...1@.X 
~~~

**Comment by andrewbird** [comment]
Think I found that I have to add on the load address 0x0060

**Comment by stsp** [comment]
There is an offset, namely, 0x600 (freedos load address).
However, let me show you a life-hack that will allow
you to not use the map file.
```
(gdb) p os_release
No symbol "os_release" in current context.
(gdb) p __os_release
$1 = {<ArSymBase<char const, 0>> = {sym = {ptr = {off = 2736, 
        seg = 217}}}, <No data fields>}
(gdb) p &lowmem_base[(__os_release.sym.ptr.seg<<4)+__os_release.sym.ptr.off]
$2 = (uint8_t *) 0x7fffc2ef1840 "FDPP kernel - GIT (build 0001) [compiled Jul  3 2018]"
```

So, when some symbol is not found by
gdb, try to find its descriptor by prepending
2 underscores. From that descriptor you'll
find its type (`char const` in the example above,
but can be any aggregate) and a far ptr.

**Comment by andrewbird** [comment]
very nice, thanks!

**Comment by andrewbird** [comment]
So with CDSp what do I `p`?
~~~
(gdb) p __CDSp
$5 = {ptr = {<FarPtrBase<FarPtrBase<cds> >> = {ptr = {off = 60, seg = 217}}, 
    obj = std::shared_ptr<ObjIf> (empty) = {get() = 0x0}, nonnull = false}}
~~~

**Comment by andrewbird** [comment]
I presume the result should be the same as with the DOS method?
~~~
dosdebug> d 00d9:003c
dosdebug> 

00d9:003c 00 00 64 04 00 00 00 00 00 00 04 1A 52 05 70 00  ..d.........R.p.
00d9:004c 04 80 B6 0E BB 0E 4E 55 4C 20 20 20 20 20 00 00  ..6.;.NUL     ..
00d9:005c 00 00 00 00 00 00 00 00 00 0A 00 01 00 03 03 00  ................
00d9:006c 00 D8 12 8A 02 00 00 00 00 00 00 00 00 00 CC 14  .X............L.
00d9:007c D9 00 00 00 00 00 00 00 FF 00 00 00 00 00 00 00  Y..............
00d9:008c FF FF 00 00 0A 07 0A 07 00 00 B0 0A 00 00 00 00  ........0.....
00d9:009c 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
00d9:00ac 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
dosdebug> d 0464:0000
dosdebug> 

0464:0000 41 3A 5C 00 00 00 00 00 00 00 00 00 00 00 00 00  A:\.............
0464:0010 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0464:0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0464:0030 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0464:0040 00 00 00 00 40 EC 18 D9 00 FF FF FF FF FF FF 02  ....@l.Y..
0464:0050 00 00 00 00 00 00 00 00 42 3A 5C 00 00 00 00 00  ........B:\.....
0464:0060 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0464:0070 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
~~~

**Comment by stsp** [comment]
```
(gdb) p __CDSp
$6 = {ptr = {<FarPtrBase<FarPtrBase<cds> >> = {ptr = {off = 60, seg = 217}}, 
    obj = std::shared_ptr<ObjIf> (empty) = {get() = 0x0}, nonnull = false}}
(gdb) p *(far_s*)&lowmem_base[(217<<4)+60]
```
Then you do `p *(cds*)&lowmem_base[...`

**Comment by andrewbird** [comment]
I ended up with this, not quite the style of yours though.
~~~
(gdb) p *(struct cds *)  &lowmem_base[(0x0464<<4) + 0x58*2]
$9 = {cdsCurrentPath = "C:\\", '\000' <repeats 63 times>, cdsFlags = 49280, cdsDpb = {ptr = {
      off = 6508, seg = 217}}, _cdsUnion = {_cdsRedirRec = {ptr = {off = 0, seg = 65535}}, _cdsRedir = {
      _cdsStrtClst = 0, _cdsParam = 65535}}, cdsStoreUData = 65535, cdsBackslashOffset = 2, 
  cdsNetFlag1 = 0 '\000', cdsIfs = {ptr = {off = 0, seg = 0}}, cdsNetFlags2 = 0}
~~~

**Comment by stsp** [comment]
You should now be able to access the symbols directly.

**Comment by andrewbird** [comment]
Was about to try, but I just used autoconf for the first time on my Bionic machine and it has some issues.

**Comment by stsp** [comment]
It seems you need to disable `emufs.sys` to
avoid autoexec.bat hang.

**Comment by andrewbird** [comment]
That and some other config.sys lines are using `e:` and as the redirector isn't working would that cause the issue?

**Comment by stsp** [comment]
Likely not.
umb.sys is absolutely harmless and still uses E.

**Comment by andrewbird** [comment]
I want to set a break in a context that can see CDSp , where do you suggest?

**Comment by stsp** [comment]
I think with my recent patch it is visible
everywhere? Or if you want any context
where it is _first_ became visible, use
FreeDOSmain. OTOH at that point it will
be NULL.

**Comment by andrewbird** [comment]
Does it work for you, I see only?
~~~
(gdb) p CDSp
No symbol "CDSp" in current context.
(gdb) p __CDSp
$1 = {ptr = {<FarPtrBase<FarPtrBase<cds> >> = {ptr = {off = 60, seg = 217}}, 
    obj = std::shared_ptr<ObjIf> (empty) = {get() = 0x0}, nonnull = false}}
~~~

**Comment by andrewbird** [comment]
As an aside, I just ran a standard freedos kernel in the same DOS installation, and you can see that the config.sys lines that reference `e:` don't work. I don't know how they could the MFS init is done in post boot now and config,sys is before that. Originally it used to init on first file open, but that got canned.
![stdfreedos](https://user-images.githubusercontent.com/220835/42842026-e5b26080-8a03-11e8-9661-d2a7fb03ba68.png)

**Comment by andrewbird** [comment]
Perhaps my disk setup is not normal, where would `e:` be?

**Comment by stsp** [comment]
In `~/.dosemu/drives` as usual.
I don't see a problem as E should be on fatfs.
But you only have C and D.

**Comment by andrewbird** [comment]
okay, that explains why you have to disable emufs.sys and I don't :smile:

**Comment by stsp** [comment]
Have you fixed the setup?
