### ISSUE TITLE
dbgsym packages should build automatically

### ISSUE THREAD

**Issue by stsp** [stsp/fdpp#21]
But they are not!
So I added this patch: ac8b689add77ba75efd62d30d71cb05aa984ef4d
@skitt could you please help me? :)
Once again I don't understand why the
debug packages are not automatically built.
Same thing was with dosemu in the past,
but now for dosemu they are built automatically,
and I can't find the difference! :(

**Comment by stsp** [comment]
@fstirlitz maybe you know what's going
on here? I wasn't able to get the debuginfo
by default from dosemu2 too, before your
patch. But I can't find any magic in it. And
the same thing happens here: no debug
info unless the -dbg package is explicitly
built. That's crazy.

**Comment by fstirlitz** [comment]
```diff
diff --git i/fdpp/clang.mak w/fdpp/clang.mak
index c4f86aa..c606d16 100644
--- i/fdpp/clang.mak
+++ w/fdpp/clang.mak
@@ -26,7 +26,7 @@ ALLCFLAGS += -ggdb3 -O2
 endif
 
 CFLAGS=$(ALLCFLAGS)
-LDFLAGS=-shared -Wl,-Bsymbolic
+LDFLAGS=-shared -Wl,-Bsymbolic -Wl,--build-id=sha1
 CLC = clang
 
 ALLCFLAGS:=$(ALLCFLAGS) -DI386
```

GCC sets this option by default.
