### ISSUE TITLE
[Question] Testing FDPP

### ISSUE THREAD

**Issue by andrewbird** [stsp/fdpp#31]
I'm thinking about adding FDPP to my dosemu test suit.

# What does ver /r relate to?
One boot test checks the version string, but I want to know what part of fdpp that relates to: the DOS boot code or the libfdpp.so?

~~~
C:\>ver /r
 
FreeCom version 0.84-pre2 XMS_Swap [Aug 28 2006 00:29:00]
DOS version 7.10
FDPP kernel - GIT (build 0001) [compiled Oct 14 2018]
C:\>
~~~

# Packaging DOS for testing
With other DOSes my test suite unpacks a tar file that contains everything for the tests on that OS such as IO.SYS MSDOS.SYS COMMAND.COM etc. But on FDPP there's an additional complication in that there's libfdpp.so to consider.
- Do you think it's possible to have the matching libfdpp.so bundled with the fdkrnl.sys and use LD_PRELOAD or LD_LIBRARY_PATH to force dosemu to pick that up in preference to any system installed copy?
- What are the implications to dosemu of running with a different copy of libfdpp.so that what it was compiled against?

**Comment by stsp** [comment]
version string currently resides in a sys
file, but they are tightly coupled. I think it
is safe to consider it the version of both,
if you dont do the manual install of either.
I dont think manual install with ld.so
tricks is a good idea, because dosemu2
can load fdpp only if it was already built
with one. In this case fdpp is already
installed and ready to run. You dont
need to install it again. So your tarball
can be empty in this case.
Running with different version will
either work correctly or trigger the abi
version check failure, depending on a
presence of incompatible changes.

**Comment by andrewbird** [comment]
Okay, thanks. I also thought afterwards that bundling the libfdpp.so into the tarball was a bad idea as it has to match 32/64 'bitness' of the platform the test was being run on, so wouldn't be portable. That said I like the tests to be reproducible and have checksums on boot files, so long term PASS/FAIL trends can be identified for Dosemu. I don't think running tests against whatever version of fdpp is installed fits with that. Oh, what to do?!

**Comment by stsp** [comment]
I think we need cooperation with dosemu.
For example it should write the fdpp git
hash to a log, and you pick it from there.

**Comment by stsp** [comment]
Or git hash can be passed to ver /r.

**Comment by andrewbird** [comment]
I have so many tests that do things with specific drive mappings that I can't use your standard drive layout. So I need to populate my specific boot drive with the correct fdppknrl.sys that matches the libfdpp.so in use. I wonder if you could populate a variable in fdpp.pc for me? I could probably abuse fdpplibdir and add the kernel name, but at some point you might change its location. What do you think?

~~~
 env PKG_CONFIG_PATH=`pwd`/pkgconfig pkg-config fdpp --variable=fdppknrl
/clients/common/fdpp.git/fdpp/fdppknrl.sys
~~~

Then I can exclude the kernel in my tarball, but include the COMMAND.COM and other support files, then copy it in to the correct drive at test setup.

**Comment by stsp** [comment]
Git hashes of those 2 should usually match.
So I suppose providing them in the log
AND ver /r will also allow to check for
mismatches. Or maybe I should add some
checks into libfdpp.so to refuse to load
a mismatched kernel, but then I suspect
people will accuse me in gpl violation
(gpl asks to run whatever the user have
modified).

I dont understand the problem with
standard layout. I suppose you cant
use it because dosemu does not
create it automatically with altered
libdir path. I think this should be fixed.
Then your tests can just start from
an empty dir.

**Comment by stsp** [comment]
So it would be best if you dont do things
on your own, hacking around the
limitations, but rather open a bugs/prs
with what you need to be solved to
avoid the problems. The entire idea
of fdpp is to avoid hacking around the
freedos problems. Lets just extend
things.

**Comment by andrewbird** [comment]
it's not a problem with your standard layout per se, I'm sure that's fine for general use, but rather that I need the flexibility to define drive mappings as I wish for each test. For instance during some of my MFS tests I boot on C: then map D: to a data drive then do file open/read/write tests on the D: drive etc. This has to work for all the flavours of DOS, not just FreeDOS or FDPP etc. Locking down to a specific layout of D: E: and F: isn't going to work across them all.

The pkgconfig variable suggestion was an attempt to fit in with the scheme of having fdppkrnl.sys located with the libfdpp.so yet have its location discoverable at run time. There may be other solutions like have dosemu.bin have a switch that prints the location and exit. That's probably less prone to inaccuracy as the PKG_CONFIG_PATH value might change between build and test.

**Comment by stsp** [comment]
How about using the drives from H etc?
I dont suppose you need exactly D E F?
The fact that fdpp kernel now loadable
from C, was an accident from my recent
changes. It may disappear again. Because
this is prone to mismatches.

**Comment by stsp** [comment]
Also you can actually remap D because
kernel is already loaded when test runs.

**Comment by stsp** [comment]
Likely not what you need, as this will
only free E, not D

**Comment by andrewbird** [comment]
> I will think about loading fdpp as a
complete phantom, w/o allocating a
drive for it. Is this what you need?

Yes that would be fine. How would the use override it though to boot something else? Perhaps the presence of other boot files would be enough.

If I have no .lnk files the other drives will be free.

**Comment by andrewbird** [comment]
How about fdppkrnl.sys being an empty file on boot drive, then when we boot we read the real file contents?

**Comment by stsp** [comment]
How will phantom help if it only frees E?
Why do you need a specific letters at all?
lredir2 has an option to allocate first free
drive.

**Comment by andrewbird** [comment]
First run, Note: FCB tests fail on FreeDOS, Image file and boot.blk tests make no sense with FDPP so I'll convert those into SKIPs for FDPP.

~~~
Test PP-DOS-1.00 FAT12 image file ... FAIL
Test PP-DOS-1.00 FAT12 image file D writable ... FAIL
Test PP-DOS-1.00 FAT12 vfs directory ... ok
Test PP-DOS-1.00 FAT12 vfs directory boot.blk ... FAIL
Test PP-DOS-1.00 FAT16 image file ... FAIL
Test PP-DOS-1.00 FAT16 image file D writable ... FAIL
Test PP-DOS-1.00 FAT16 vfs directory ... ok
Test PP-DOS-1.00 FAT16 vfs directory boot.blk ... FAIL
Test PP-DOS-1.00 FAT16B image file ... FAIL
Test PP-DOS-1.00 FAT16B vfs directory ... ok
Test PP-DOS-1.00 FAT16B vfs directory boot.blk ... FAIL
Test PP-DOS-1.00 FAT32 disk info ... ok
Test PP-DOS-1.00 FAT AUTO vfs directory ... ok
Test PP-DOS-1.00 Floppy image file ... SKIP: Image signature not available
Test PP-DOS-1.00 Floppy vfs directory ... ok
Test PP-DOS-1.00 INT21 disk info ... ok
Test PP-DOS-1.00 LFN volume info on FAT(img) ... FAIL
Test PP-DOS-1.00 LFN volume info on MFS ... ok
Test PP-DOS-1.00 MFS auto hd vfs directory redirection ... ok
Test PP-DOS-1.00 MFS FCB file rename simple ... FAIL
Test PP-DOS-1.00 MFS FCB file rename source missing ... FAIL
Test PP-DOS-1.00 MFS FCB file rename target exists ... FAIL
Test PP-DOS-1.00 MFS FCB file rename wildcard one ... FAIL
Test PP-DOS-1.00 MFS FCB file rename wildcard two ... FAIL
Test PP-DOS-1.00 MFS FCB file rename wildcard three ... FAIL
Test PP-DOS-1.00 MFS FCB file rename wildcard four ... FAIL
Test PP-DOS-1.00 MFS LFN directory change current ... ok
Test PP-DOS-1.00 MFS LFN directory create ... ok
Test PP-DOS-1.00 MFS LFN directory delete ... ok
Test PP-DOS-1.00 MFS LFN directory delete not empty ... ok
Test PP-DOS-1.00 MFS LFN file append ... ok
Test PP-DOS-1.00 MFS LFN file create ... ok
Test PP-DOS-1.00 MFS LFN file create readonly ... ok
Test PP-DOS-1.00 MFS LFN file find ... ok
Test PP-DOS-1.00 MFS LFN file read ... ok
Test PP-DOS-1.00 MFS LFN file truncate ... ok
Test PP-DOS-1.00 MFS LFN get current directory ... ok
Test PP-DOS-1.00 MFS LFN Truename ... ok
Test PP-DOS-1.00 MFS lredir2 command redirection ... ok
Test PP-DOS-1.00 MFS SFN directory change current ... ok
Test PP-DOS-1.00 MFS SFN directory create ... ok
Test PP-DOS-1.00 MFS SFN directory delete ... ok
Test PP-DOS-1.00 MFS SFN directory delete not empty ... ok
Test PP-DOS-1.00 MFS SFN file append ... ok
Test PP-DOS-1.00 MFS SFN file create ... ok
Test PP-DOS-1.00 MFS SFN file create readonly ... ok
Test PP-DOS-1.00 MFS SFN file find ... ok
Test PP-DOS-1.00 MFS SFN file read ... ok
Test PP-DOS-1.00 MFS SFN file truncate ... ok
Test PP-DOS-1.00 MFS SFN get current directory ... ok
Test PP-DOS-1.00 MFS SFN Truename ... ok
Test PP-DOS-1.00 SysType ... ok
Test PP-DOS-1.00 Three vfs directories configured ... ok
~~~

> How will phantom help if it only frees E?

Because I use no `.lnk` files all drives are free to use, the only difficulty is getting `fdppkrnl.sys` on the boot drive.

> Why do you need a specific letters at all?

Not all tests are done with MFS, some are fatfs.

It's okay as is, I can live with it now as long as you don't disallow `fdppkrnl.sys` boot from `C:`

**Comment by stsp** [comment]
> It's okay as is, I can live with it now as long as you don't disallow fdppkrnl.sys boot from C:

OK, since I have no plans to intentionally break
your test-suit, and given the fact you were first
to discover that bug and use it, let's say I won't
remove it willingly. :)
Phantom loading is probably too difficult to worth
the troubles.
I will probably add the git hash compare to libfdpp.so
instead then.

So basically only fcb fails, right?
Which might explain why I do not trigger any
bugs myself recently. Would be nice if you
open the reports to fdpp with the test-case,
so that I can port the fcb code. But I have
other short-term plans for now. Like fixing
the simple bugs (like the one you reported
about different results with freedos), releasing
beta2, work on the core (memory management,
object trackers, UBs etc), writing some more docs.
So if you take a look on an fcb stuff yourself,
that would be awesome. :)

What do you think of fdpp, other than what testing
shows? For me it works pretty reliably, so...

**Comment by andrewbird** [comment]
Yes, I'm going to look at the FCB issues, FreeDOS is broken too but I'll write the patch for FDPP as it seems nobody cares about FreeDOS issues.

What do you think about allowing fdppkrnl.sys to be an empty file and reading real data from the proper file at runtime? I could write that, but only if you don't hate the idea :smile:

FDPP seems okay to me, but I haven't run any apps on it yet only my tests.

**Comment by stsp** [comment]
I don't think empty file is any better than what we
currently have (non-empty file loads too). Plus that
would still mean some hacks in fatfs.c, as currently
it just loads the file, and for some DOSes even looks
inside. So basically you will still need fatfs.c to call
into fdpp.c, asking for a custom load procedure. I
don't see this being any better than doing so when
there are no system files at all.
