### ISSUE TITLE
FDPP gets confused about boot drive

### ISSUE THREAD

**Issue by andrewbird** [stsp/fdpp#32]
Booting the same disk configuration under FreeDOS and FDPP gives different results. On FreeDOS the boot proceeds as expected, on FDPP it can't find the files referenced in config.sys or autoexec.bat itself.
### FreeDOS 1.20
![fd-120](https://user-images.githubusercontent.com/220835/46953051-9478b800-d084-11e8-8021-e548397ddf07.png)

### FDPP from git
![fdpp](https://user-images.githubusercontent.com/220835/46953079-ac503c00-d084-11e8-831d-5cb4ebcdf356.png)

I've attached the installation files 
[test-imagedir.tar.gz](https://github.com/stsp/fdpp/files/2478848/test-imagedir.tar.gz)

Run from dosemu build directory as 
~~~
bin/dosemu.bin -n -f test-imagedir/dosemu.conf -D+dRW -o test.log --Fimagedir test-imagedir
~~~

Firstly with your `fdppkrnl.sys` in `test-imagedir/dXXXXs/c` then replace that with `kernel.sys` from FreeDOS 1.20

**Comment by stsp** [comment]
How about using the full path to emufs.sys?

**Comment by andrewbird** [comment]
Yes, but that's a symptom. It can't find autoexec.bat and lands on the D: drive afterwards.

**Comment by stsp** [comment]
Try `fdconfig.sys` instead of `config.sys`

**Comment by andrewbird** [comment]
Yes renaming config.sys to fdconfig.sys worked, why?

**Comment by stsp** [comment]
The fdpp boot procedure differs a lot from
all other boot procedures.
dosemu2 looks for different files for fdpp
(fdconfig.sys, command.com), and points fdpp
to them. So the bug is not here, but in dosemu2.
I'll look at what happens.

**Comment by stsp** [comment]
This is now fixed.
The problem was the presence of a hdimage,
for which I assumed the presence of all needed
files (because of the inability to look inside).
If that hurts, I stopped doing so.

**Comment by andrewbird** [comment]
That's looking a lot better thanks
~~~
Test PP-DOS-1.00 FAT12 image file ... SKIP: Booting from image not supported
Test PP-DOS-1.00 FAT12 image file D writable ... ok
Test PP-DOS-1.00 FAT12 vfs directory ... ok
Test PP-DOS-1.00 FAT12 vfs directory boot.blk ... SKIP: Not supported by Boot Block
Test PP-DOS-1.00 FAT16 image file ... SKIP: Booting from image not supported
Test PP-DOS-1.00 FAT16 image file D writable ... ok
Test PP-DOS-1.00 FAT16 vfs directory ... ok
Test PP-DOS-1.00 FAT16 vfs directory boot.blk ... SKIP: Not supported by Boot Block
Test PP-DOS-1.00 FAT16B image file ... SKIP: Booting from image not supported
Test PP-DOS-1.00 FAT16B vfs directory ... ok
Test PP-DOS-1.00 FAT16B vfs directory boot.blk ... SKIP: Not supported by Boot Block
Test PP-DOS-1.00 FAT32 disk info ... ok
Test PP-DOS-1.00 FAT AUTO vfs directory ... ok
Test PP-DOS-1.00 Floppy image file ... SKIP: Booting from image not supported
Test PP-DOS-1.00 Floppy vfs directory ... ok
Test PP-DOS-1.00 INT21 disk info ... ok
Test PP-DOS-1.00 LFN volume info on FAT(img) ... ok
Test PP-DOS-1.00 LFN volume info on MFS ... ok
Test PP-DOS-1.00 MFS auto hd vfs directory redirection ... ok
~~~

**Comment by stsp** [comment]
Thanks for taking care of this.
