### ISSUE TITLE
FDPP aborts on exit / termination of PC/GEOS 

### ISSUE THREAD

**Issue by bolle732** [stsp/fdpp#40]
The good news first:
PC/GEOS starts up with "fdppkrnl.sys" and works fine as far I've tested it. That's really great!

But when I leave / exit PC/GEOS for returning to DOS, I get a crash of FDPP / DOSEMU2.

[boot-fdpp.log](https://github.com/stsp/fdpp/files/2542096/boot-fdpp.log)
 (boot.log has been renamed and shortened due to lots of dispatch lines)

My manual setup of drive_c use the current "fdppkrnl.sys" from GIT (20181102) and the "command.com" from FreeDOS (0.84-pre2).

I'd liked to try comcom32 too, but I'm still unable to compile it. Maybe someone has a short hint which Debian packet has the right compiler or where can I get a precompiled one.

**Comment by stsp** [comment]
First, thanks for testing our new stuff!
There are really very few people doing so,
and that's bad. Knowing that FDPP already
runs geos, is indeed the great news.
Second, here's the comcom32:
[comcom32.exe.gz](https://github.com/stsp/fdpp/files/2542175/comcom32.exe.gz)

I hope you don't have any convoluted bat
files, as comcom32 is very limited in features.
If you have fedora, then building comcom32
is not a problem, but not so good on ubuntu,
so use a binary from here for now.

**Comment by stsp** [comment]
`Reading symbols from /usr/local/bin/dosemu.bin...(no debugging symbols found)...done.`
Please fix this.

**Comment by stsp** [comment]
> PC/GEOS starts up with "fdppkrnl.sys"

That's a bit confusing btw, are you putting
fdppkrnl.sys on C: by hands, or what? You
shouldn't be doing anything like that. dosemu2
finds the needed files on its own. So I am
surprised you mention the file name, you
should never see it.

**Comment by andrewbird** [comment]
Not to hijack this thread, but seeing as you are discussing it anyway, for me FDPP no longer boots with `fdppkrnl.sys` with --Fimagedir set when I want to run without system install.

**Comment by bolle732** [comment]
@stsp
Strange that there are no symbols, I need to investigate it. I have "debug on" specified in "compiletime-settings".

```
file /usr/local/bin/dosemu.bin
/usr/local/bin/dosemu.bin: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=55bf1c132d7001a73a4f80d3676edfcc99f6a46c, not stripped
```
Is there any debug setting in fdpp ?

Thank you for providing the "comcom32.exe". How do I activate it ? Replacing "command.com" with it does not work. Is there a specific option in "dosemu.conf" ? I'm on Ubuntu 16.04 64-bit.

@andrewbird 
I use the "--Fimagedir" too. I had is some confusion when compiling. As far I understand, one has to compile and install "fdpp" first and then compile and install "dosemu2". In my manual setup, I've copied the current version of "fdppkrnl.sys" to the "drive_c".

Here is my "dosemurc" and start script:
[dosemurc.txt](https://github.com/stsp/fdpp/files/2542389/dosemurc.txt)
[start.sh.txt](https://github.com/stsp/fdpp/files/2542390/start.sh.txt)

You have to remove the ".txt" extemsion and set it up for your need.

**Comment by stsp** [comment]
> fdppkrnl.sys with --Fimagedir set when I want to run without system install.

But I already wrote to you in another thread
that you need to use `FDPP_KERNEL_DIR`
variable, as I reverted all the other hacks.

> Is there any debug setting in fdpp ?

Debug for fdpp is enabled by default, and is
enabled in your log too. Only dosemu debug
is disabled "not stripped" doesn't mean the
debug info is present, it only means you didn't
use `strip` to remove it.

**Comment by bolle732** [comment]
> Debug for fdpp is enabled by default, and is
enabled in your log too. Only dosemu debug
is disabled "not stripped" doesn't mean the
debug info is present, it only means you didn't
use strip to remove it.

Thank you for recalling the fact about "strip". I forgot the `./default-configure` after the `git pull`...

Here the `boot.log` with `Reading symbols from /usr/local/bin/dosemu.bin...done.`
[boot.log](https://github.com/stsp/fdpp/files/2542466/boot.log)

**Comment by stsp** [comment]
> file /usr/local/bin/dosemu.bin

Please use `gdb /usr/local/bin/dosemu.bin`
instead. It will tell you if no debug info.

**Comment by stsp** [comment]
OK, looking.

**Comment by andrewbird** [comment]
Ahh sorry for the noise, I must have missed that change as it's working with this.
~~~
env FDPP_KERNEL_DIR=test-imagedir/dXXXXs/c bin/dosemu.bin -n -f test-imagedir/dosemu.conf -D+dRWD -o test.log --Fimagedir test-imagedir -I"cpuemu fullsim"
ERROR: dosemu2 commands not found at /usr/local/share/dosemu/dosemu2-cmds-0.2
ERROR: Your fluidsynth is too old and soundfonts not found
ERROR: alsa_midi (ALSA lib): rawmidi_hw.c:233:(snd_rawmidi_hw_open) : No such file or directory open /dev/snd/midiC0D0 failed
ERROR: fdpp booting, this is very experimental!
~~~

**Comment by andrewbird** [comment]
@bolle732 thanks for the scripts and config, it's always interesting to see what options other people are using.

**Comment by stsp** [comment]
```
ERROR: dosemu2 commands not found at /usr/local/share/dosemu/dosemu2-cmds-0.2
ERROR: Your fluidsynth is too old and soundfonts not found
ERROR: alsa_midi (ALSA lib): rawmidi_hw.c:233:(snd_rawmidi_hw_open) : No such file or directory open /dev/snd/midiC0D0 failed
ERROR: fdpp booting, this is very experimental!
```

And with all that it still works...

**Comment by bolle732** [comment]
> > PC/GEOS starts up with "fdppkrnl.sys"
> 
> That's a bit confusing btw, are you putting
> fdppkrnl.sys on C: by hands, or what? You
> shouldn't be doing anything like that. dosemu2
> finds the needed files on its own. So I am
> surprised you mention the file name, you
> should never see it.

Yes, I have it in the root of "drive_c".
Otherwise I get `ERROR: Bootable drive not found, exiting`.

I do `sudo make install` in both fdpp and dosemu2.

**Comment by bolle732** [comment]
It's installed under `/usr/local/share/fdpp/fdppkrnl.sys`, but it does't get found.

**Comment by bolle732** [comment]
> That's because you don't have the default
> drive layout. I think it is not being created in
> an altered libdir, which is likely a bug.
> If so - please fill in the ticket.

Do you mean the libdir of DOSEMU2 used for it's plugins or the imagedir ?

**Comment by bolle732** [comment]
> First, thanks for testing our new stuff!
> There are really very few people doing so,
> and that's bad. Knowing that FDPP already
> runs geos, is indeed the great news.
> Second, here's the comcom32:
> [comcom32.exe.gz](https://github.com/stsp/fdpp/files/2542175/comcom32.exe.gz)
> 
> I hope you don't have any convoluted bat
> files, as comcom32 is very limited in features.
> If you have fedora, then building comcom32
> is not a problem, but not so good on ubuntu,
> so use a binary from here for now.

How does DOSEMU2 find the comcom32.exe ? Still trying to figure that out...

**Comment by bolle732** [comment]
Ok, found it. Now it seems that my custom dirs don't work anymore. Have to investigate more...

**Comment by stsp** [comment]
You can just put it to C and symlink
as command.com. Install will complain
but boot will find it. They have a different
search logic.

**Comment by stsp** [comment]
Should now be fixed.

**Comment by stsp** [comment]
Please use FDPP_KERNEL_DIR for
custom dirs, as Andrew's example above
does.

**Comment by bolle732** [comment]
I have a broken link in `~/.dosemu/drive_c` which I havn't created myself:

`command.com -> /usr/local/share/comcom32/command.com`

I copied `comcom32.exe` to the folder `/usr/local/share/comcom32`, but I don't have the `command.com` there.

Is this due to my manual setup ? Is `/usr/local/share/comcom32/command.com` a link to `comcom32.exe` ?

**Comment by stsp** [comment]
> Is this due to my manual setup ? Is /usr/local/share/comcom32/command.com
> a link to comcom32.exe ?

Yes, please. Link it yourself and all be well.
Symlink drive_c/command.com is created for
compatibility with freedos, which can only boot
from C mostly. fdpp has an ability to boot from
any drive layout: kernel from E, command.com
from F, config.sys from D - that's the default
fdpp boot layout under dosemu2, but it can
find these files on any other drives too.
So you can either remove that symlink or
leave it - boot logic will find it if its there, or
look in other places.

**Comment by bolle732** [comment]
I've been fighting with comcom32 and it's "install" of the drives in `~/.dosemu`. That's why I didn't reported back earlier.

Regarding the problem of this issue here, I can confirm, that it's fixed. Now, I can start and end PC/GEOS multiple times without a crash. Thanks a lot for that!

PS:
Nice that fdpp use about 200 bytes less memory in comparison to the FreeDOS kernel ;-)

**Comment by stsp** [comment]
So what was the problem with comcom32?
Better memory use is unexpected because
fdpp reserves 1K of memory and does not
relocate it. Which means you can expect
even more free mem later when I get to
fixing that.

**Comment by bolle732** [comment]
For short:
When I have the `/usr/local/share/comcom32/comcom32.exe` in place, it triggers the install of the files in `~/.dosemu`. After that, I'm unable to start DOSEMU2 with an installation in another folder then `~/.dosemu`.
To get back my setup working again, I have to rename the folder `/usr/local/share/comcom32` and do need to do an `rm -rf ~/.dosemu/drive*`.

**Comment by stsp** [comment]
Please open a bug for this, describing
what exactly doesnt work and how.

**Comment by bolle732** [comment]
I think, we can close this issue. What do you think ?

**Comment by stsp** [comment]
Its closed.
