### ISSUE TITLE
dosemu2 crashes when running DataRescue IDA 3.7 freeware installer

### ISSUE THREAD

**Issue by tkchia** [stsp/fdpp#48]
**Describe the bug**
`dosemu2` crashes when I try to run the installer for DataRescue IDA 3.7 freeware.

```
ERROR: Fault in dosemu code, in_dpmi=0
ERROR: cpu exception in dosemu code outside of VM86()!
sig: 8 trapno: 0x00  errorcode: 0x00000000  cr2: 0x00000000
eip: 0x7fd3dde9db61  esp: 0x7fd3c48a6c10  eflags: 0x00010246
cs: 0x0033  ds: 0x0000  es: 0x0000  ss: 0x0000
fs: 0x0000  gs: 0x0000
fsbase: 0x7fd3dfc37700 gsbase: (nil)

ERROR: Please install gdb, update dosemu from git, compile it with debug
info and make a bug report with the content of ~/.dosemu/boot.log at
https://github.com/stsp/dosemu2/issues
Please provide any additional info you can, like the test-cases,
URLs and all the rest that fits.
```

**To Reproduce**
  * Unpack `ida37fw.zip` (below).
  * Run `install.exe` under `dosemu2` like so: `dosemu -D9+D -t -quiet -K install.exe`.
  * Under `install.exe`, select "Install Program".

**Attach the binaries**
  * [`ida37fw.zip`](https://github.com/stsp/dosemu2/files/2749862/ida37fw.zip) (also available [at `textfiles.com`](http://cd.textfiles.com/simtel/simtel0101/simtel/disasm/ida37fw.zip)).

**Attach the log**
  * [`boot.log`](https://github.com/stsp/dosemu2/files/2749870/boot.log).

**Comment by stsp** [comment]
Hmm!
Poof and this ticket is in an fdpp repo. :)
OKey, at least MS brings some interesting
new features to github.
