### ISSUE TITLE
call previous inthandlers

### ISSUE THREAD

**Issue by stsp** [stsp/fdpp#53]
Currently fdpp (and freedos) hooks the
interrupts and does not call the previous
handlers (set by BIOS).
Make it so that it does.

**Comment by andrewbird** [comment]
Will you make It use IBM interrupt sharing?

**Comment by stsp** [comment]
It seems, freedos does this:
```
  for (i = 0x23; i <= 0x3f; i++)
    setvec(i, empty_handler);
```
... which is iret.
Just removing that hunk will already
redirect many handlers (including 0x33)
even w/o any sharing.
As for other handlers, sharing header may
be difficult, because the handlers look like this:
```
                global  _int2f_handler
                extern  reloc_call_int2f_handler
_int2f_handler: jmp 0:reloc_call_int2f_handler
                call near forceEnableA20
```
This is a PLT, 0 is patched later with the
segment of `reloc_call_int2f_handler`, and
you can't insert anything here.
Of course we can try to change the format
of the relocation table, so that we can insert
various stuff in it, and all that. Or we can do
it the MS-DOS's way, which is to re-hook int
vectors on relocations, so that the vectors
always point to the real handler, not to the jump.
Would be nice to do that, but I wonder if the
relocation scheme is intentionally obfuscated,
for example I can see the code:
```
        struct RelocatedEntry FAR *rel = (struct RelocatedEntry FAR *)rp;
    
        fmemcpy_n(&rtemp, rp, sizeof(rtemp));
          
        rel->jmpFar = rtemp.jmpFar;
        rel->jmpSegment = NewKernelSegment;
        rel->jmpOffset = rtemp.jmpOffset;
        rel->callNear = rtemp.callNear;
        rel->callOffset = rtemp.callOffset + 5; /* near calls are relative */
```
... which seemingly swaps places of call and jump,
because `rp` is `struct RelocationTable` while
`rel` is `struct RelocatedEntry`, and here are the defs:
```
struct RelocationTable {
  UBYTE jmpFar;
  UWORD jmpOffset;
  UWORD jmpSegment;
  UBYTE callNear;
  UWORD callOffset;
} PACKED;

struct RelocatedEntry {
  UBYTE callNear;
  UWORD callOffset;
  UBYTE jmpFar;
  UWORD jmpOffset;
  UWORD jmpSegment;
} PACKED;
```

Crazy, isn't it?
If you want to clean this up, then we definitely
will end up with shared headers and all the goodies. :)

**Comment by stsp** [comment]
> Will you make It use IBM interrupt sharing?

Should now be possible, and I already added some.
