### ISSUE TITLE
[Question] what is the LFNAPI in FreeDOS / FDPP?

### ISSUE THREAD

**Issue by andrewbird** [stsp/fdpp#57]
I started wondering if at least FDPP could cooperate with Dosemu2 regarding LFN. I see there are ifdef'ed `WITHLFNAPI` sprinkled around. But I'm not sure exactly what that does implement. For example I see
 https://github.com/stsp/fdpp/blob/b197c40bb95f49bbd4b45fc12992474b30b47143/kernel/inthndlr.c#L1540

But what's int21/74xx I don't see that in RBIL?

**Comment by stsp** [comment]
It calls functions from `lfnapi.c`, which, itself,
calls the functions that do not exist at all.
So this is something never written/outdated.
No idea why it was bound to 0x74. I think it
was supposed only for local FAT, not seems
to be going to the redirector.
I think if we want to improve the LFN support,
we need to design it from scratches. I don't
know if something can be borrowed from
fat-specific, not written impl.

**Comment by stsp** [comment]
I think the one can try to think up the int2f
redirector extensions for LFN, but I suspect
the problems will happen when you try to
call that from the DOS core. The buffers in
the DOS structs (like CDS) are too small.
So you will likely need to work with SFN most
of the time, but have its LFN counterpart
available via redirector API when needed.
This is a serious research topic, unless some
other DOS already tried something like that.
Would be cool if you investigate that, but we
have plenty of the short-term work to do, too. :)

**Comment by andrewbird** [comment]
Thanks for figuring out what it was, I suspect it's not even compiled in by default.
Yes, quite right, there are too many other things to do first. I'll close for now.

**Comment by stsp** [comment]
It cant be compiled.
