### ISSUE TITLE
Unable to open file 'C:\:COMMAND.COM'

### ISSUE THREAD

**Issue by ZoccoCss** [stsp/fdpp#64]
I updated and compiled to the latest version and I'm getting a the following message Unable to open file 'C:\:COMMAND.COM'

![Screenshot from 2019-04-29 08-35-36](https://user-images.githubusercontent.com/47893772/56897173-c6b79900-6a5b-11e9-897e-1a555ecdf70d.png)

[boot.log.gz](https://github.com/stsp/dosemu2/files/3127417/boot.log.gz)

**Comment by ZoccoCss** [comment]
Sorry, I can't open an ssh from this computer. 

What information do you need?

**Comment by stsp** [comment]
Then please bisect (`git bisect`) the recent
fdpp patches to find out which one breaks
and when it worked last time.

**Comment by stsp** [comment]
In particular, try to go before commit a6d8ed06.
Maybe somehow it made the problem.

**Comment by stsp** [comment]
`git checkout a6d8ed06^`
and rebuild.

**Comment by stsp** [comment]
This problem was reproducible only if you
symlink freecom.exe to C: as command.com.
Why do you never tell about the custom
modifications you do? :(
Should now be fixed.

**Comment by ZoccoCss** [comment]
With the fix you made, the error is gone. Thank you. 

Don't know how that symlink was made. The only symlink I made was this one. 

"This is a "known problem" with an explanation "dosemu2 is not written yet". Some manual setup is needed. Can you build the command.com from here? https://github.com/stsp/comcom32 If not, I am attaching the binary here. comcom32.exe.gz Now do dosemu -install and when it exits again, put this comcom32.exe into ~/.dosemu/drive_c Then symlink it to command.com."

Maybe I made it incorrectly and didn't remove it when it was no longer needed.  

The only other thing that I did different this time was that I also upgraded from Debian 9.8 to 9.9.

**Comment by stsp** [comment]
No, this is not what you did.
You took freecom, not comcom32.
It is clearly written on your screen:
`FreeCom version 0,84-pre2`
I am not saying you shouldn't test the
unusual scenarios, but please describe
them next time.
Thanks for spotting the very important
bug btw.
The info you quoted about comcom32 is
outdated too.
