### ISSUE TITLE
device header is not para-aligned

### ISSUE THREAD

**Issue by stsp** [stsp/fdpp#67]
As mentioned here:
https://github.com/stsp/dosemu2/issues/817#issuecomment-488079777
the device drivers should load into a
para-aligned regions.

**Comment by stsp** [comment]
@andrewbird how can I reproduce this?
I do `devs` and see
```
c30c:0000 Char 'EMUFS$  '
  Attributes: 0x8000 (Char)
  Routines: Strategy(c30c:0036), Interrupt(c30c:0041)

c302:0000 Char 'EMMXXXX0'
  Attributes: 0xc000 (Char, IOCTL)
  Routines: Strategy(c302:003e), Interrupt(c302:0049)
```
... which looks quite aligned?

**Comment by stsp** [comment]
Can it be that with the `search` you've found the
wrong instance of the string?

**Comment by stsp** [comment]
Lets close this until there is a confirmation that
the bug exist.

**Comment by andrewbird** [comment]
Perhaps so, but I don't know why it would be loaded elsewhere and there was only one instance of the string.  But it was the UMBXXXX0 driver not EMMXXX0 and didn't stay loaded.

**Comment by stsp** [comment]
If none of the loaded drivers have this problem,
lets forget it.

**Comment by andrewbird** [comment]
Okay, no worries.
