### ISSUE TITLE
some driver (umb.sys?) is wrongly written

### ISSUE THREAD

**Issue by stsp** [stsp/fdpp#68]
In qemm's mft.exe, `First Meg`/`Programs`, I can
see the list of our drivers. `EMS` and `EMUFS` are
there. But I don't see the UMB driver (I load umb.sys),
and I see some `(C315)` instead of a driver name.
Which is the address of the loaded driver, and mft
can't get its name.

@andrewbird I guess your dosdebug extensions will
allow you to quickly find the problem here? :)

**Comment by andrewbird** [comment]
Cool, that fixed it. Yes I think it might be nice to display these. Interestingly i think knowing that drivers etc have subsegment blocks also confirms that the unaligned driver issue #67 is a [Red Herring](https://en.wikipedia.org/wiki/Red_herring) as the UMBXXX string found isn't in the initial data segment and consequently the driver must be only be moved there after successful initialisation.
