### ISSUE TITLE
LFN file create making SFN instead

### ISSUE THREAD

**Issue by andrewbird** [stsp/fdpp#80]
I'm finally trying to make some of my tests run again on FDPP. I'm seeing a problem where the LFN create test, which works fine on FreeDOS 1.20, only makes the SFN filename.

I've attached a sample to run
1/ extract [nolfncreate.zip](https://github.com/stsp/fdpp/files/3321888/nolfncreate.zip) in dosemu build directory
2/ run 
~~~
bin/dosemu.bin \
	-n -f test-imagedir/dosemu.conf -o test.log \
	--Fimagedir `pwd`/test-imagedir \
	--Flibdir `pwd`/test-libdir
~~~
3/ run `test_mfs.bat`
4/ dir d: /lfn (freecom)
5/ See the sfn only

![nolfncreate](https://user-images.githubusercontent.com/220835/60038248-b7e01200-96ab-11e9-8e6d-358d57f6cd48.png)

**Comment by stsp** [comment]
Try `$_set_int_hooks = (on)`.

**Comment by andrewbird** [comment]
Yes that works

**Comment by stsp** [comment]
Should now be fixed.
@bolle732 please make sure geos is still fine.

**Comment by andrewbird** [comment]
Cool, that fixed it for me, thanks!

**Comment by stsp** [comment]
Good to get fdpp tested.
These days I can only find the bugs there
via the code review or by recalling what ad-hocs
have I added 2 years ago when started coding it.
If feels rather stable to me otherwise
(not counting 10+ regressions I put recently).
If it passes the tests, I'll probably stop this daunting
review process.

**Comment by andrewbird** [comment]
For now I think there's not enough coverage to rely on my test suite, your review process has uncovered far more so far.

**Comment by bolle732** [comment]
> @bolle732 please make sure geos is still fine.

With LFN all seems to work so far I've tested (creating folder, moving files).

**Comment by stsp** [comment]
Thanks!

**Comment by stsp** [comment]
As a moron I've re-fixed this LFN bug again. :(

**Comment by andrewbird** [comment]
LFN tests still passing
https://travis-ci.com/stsp/dosemu2/builds/119046422
