### ISSUE TITLE
FCB Rename failing again

### ISSUE THREAD

**Issue by andrewbird** [stsp/fdpp#94]
##### Bisected to:

$ git bisect good
91ff3e3fb4e8598384451e4f89dd664ab2a29424 is the first bad commit
commit 91ff3e3fb4e8598384451e4f89dd664ab2a29424
Author: Stas Sergeev <stsp@users.sourceforge.net>
Date:   Tue Jul 23 22:10:53 2019 +0300

    int2f: rewrite redirector fns in C [fixes #86]

 kernel/int2f.asm | 93 --------------------------------------------------------
 kernel/network.c | 76 +++++++++++++++++++++++++++++++++++++++++++++
 kernel/proto.h   | 10 +++---
 3 files changed, 81 insertions(+), 98 deletions(-)

##### Test
env FDPP_KERNEL_DIR=`pwd`/../fdpp.git/fdpp nosetests -v test/test_dos.py:PPDOSGITTestCase.test_mfs_fcb_rename_simple
~~~
Test PP-DOS-GIT MFS FCB file rename simple ... FAIL

======================================================================
FAIL: Test PP-DOS-GIT MFS FCB file rename simple
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/clients/common/dosemu2.git/test/test_dos.py", line 905, in test_mfs_fcb_rename_simple
    self._test_fcb_rename_common("MFS", "simple")
  File "/clients/common/dosemu2.git/test/test_dos.py", line 852, in _test_fcb_rename_common
    self.assertIn("Rename Operation Success", results);
AssertionError: 'Rename Operation Success' not found in 'test_mfs.bat\r\r\n\r\r\nC:\\>d:\r\r\n\r\r\nD:\\>c:\\mfsfcbr1\r\r\nRename Operation Failed\r\r\nD:\\>DIR\r\r\n Volume in drive d is IR DXXXXS D\r\n Directory of d:\\\r\n\r\n2019-07-24 16:48             7 TESTA.BAT\r\n         1 file(s)              7 bytes\r\n         0 dir(s)               0 byte(s) free\r\n\r\r\nD:\\>'

----------------------------------------------------------------------
Ran 1 test in 4.525s

FAILED (failures=1)
~~~

**Comment by stsp** [comment]
Hmm, I suspect this is `SS= DOS DS` thing...

**Comment by stsp** [comment]
Could you please upload the test?

**Comment by andrewbird** [comment]
it's in my travis-ci branch of dosemu, or do you just want the binary?

**Comment by andrewbird** [comment]
Here's zip of what I grabbed from the test directory 
[tst1.zip](https://github.com/stsp/fdpp/files/3427949/tst1.zip)

**Comment by stsp** [comment]
Should now be fixed.
The aforementioned patch was innocent btw.
We just had a generic instability for that long...

**Comment by andrewbird** [comment]
thanks, tested working again.
